### ISSUE TITLE
Docker implementation

### ISSUE THREAD

**Issue by jc21** [node-ci/nci-ansible-ui#4]
I came across your project from a reddit post and it's pretty much what I'm looking for.

I run pretty much everything in Docker so I created a docker image for this: https://hub.docker.com/r/jc21/nci-ansible-ui/

Feel free to add a link in your documentation.

**Comment by okv** [comment]
That's great, I'll add a link to the doc.
I think it will be even more useful if docker image will contain preconfigured ansible user with ssh access like described [here](https://github.com/node-ci/nci-ansible-ui-quick-setup):

```yaml
ansible_host: 127.0.0.1
ansible_user: ansible
ansible_ssh_private_key_file: ~/.ssh/id_rsa_test
```

to been able to run sample playbooks without any configuration.
