### ISSUE TITLE
How can i access it over public ip instead of localhost:3000

### ISSUE THREAD

**Issue by softobizadmins** [node-ci/nci-ansible-ui#8]
I want to access the Ansible UI publically. Please help me with this.

Thanks

**Comment by okv** [comment]
You can just set `host`, and `url` at [config](https://github.com/node-ci/nci-ansible-ui-quick-setup/commit/f6c47405b69ad09bca0bf1241aa5062b1213c1b5#diff-f1bc699df4d356b69e47d3b3f18fcc68R15) to external network interface e.g.:

```yaml
http:
    host: 66.66.66.66
    port: 3000
    url: http://66.66.66.66:3000
```

or use some reverse proxy e.g. nginx
